name: etiquetado_voila
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - ipykernel
  - ipywidgets
  - isort
  - pandas>=2,<3
  - pip
  - pylint>=3,<3.1
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - python>=3.9
  - voila
  - watchdog
  - unitpackage>=0.8.4,<0.9.0
  - pip:
    - echemdbconverters>=0.2.0,<0.3.0
